# https://www.ssa.gov/locator
# url=https://secure.ssa.gov/ICON/ic001.do
# zipCodeSearched=94118
url=https://tools.usps.com/tools/app/ziplookup/zipByCityState
User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
redirects=10
tCompany=
tAddress=1 Market Street
tApt=
city=San Francisco
state=CA
mode=1